
- name: Build image and with build args
  community.general.docker_image:
    name: epflsi/ict-bot:latest
    state: present
    build:
      path: /srv/ict-bot
      dockerfile: ./ops/Dockerfile
      nocache: yes
    source: build
  tags: docker_install

- name: Container present
  community.general.docker_container:
    name: ict-bot
    state: present
    image: epflsi/ict-bot:latest
  tags: docker_install
